# (C) 2001-2024 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.

set_global_assignment -name DEVICE AGIB023R18A1E1V
set_global_assignment -name BOARD default
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 1
set_global_assignment -name ENABLE_ED_CRC_CHECK ON
set_global_assignment -name MINIMUM_SEU_INTERVAL 0
set_global_assignment -name DEVICE_INITIALIZATION_CLOCK OSC_CLK_1_125MHZ
set_global_assignment -name AUTO_RESTART_CONFIGURATION OFF
set_global_assignment -name STRATIXV_CONFIGURATION_SCHEME "AVST X8"
set_global_assignment -name USE_PWRMGT_SCL SDM_IO0
set_global_assignment -name USE_PWRMGT_SDA SDM_IO12
set_global_assignment -name USE_CONF_DONE SDM_IO16
set_global_assignment -name USE_INIT_DONE SDM_IO5
set_global_assignment -name USE_PWRMGT_ALERT SDM_IO9
set_global_assignment -name USE_HPS_COLD_RESET SDM_IO7
set_global_assignment -name VID_OPERATION_MODE "PMBUS SLAVE"
set_global_assignment -name PWRMGT_DEVICE_ADDRESS_IN_PMBUS_SLAVE_MODE 01
set_global_assignment -name GENERATE_PR_RBF_FILE ON
set_global_assignment -name PWRMGT_VOLTAGE_OUTPUT_FORMAT "LINEAR FORMAT"
set_global_assignment -name PWRMGT_LINEAR_FORMAT_N "-12"
set_global_assignment -name GENERATE_COMPRESSED_SOF ON

## Used for Example design on Devkit ##

# reset interface
set_location_assignment PIN_L31 -to resetn
set_instance_assignment -name IO_STANDARD "1.0 V" -to resetn

# fabric PLL refclk
set_location_assignment PIN_A25 -to refclk4
#set_instance_assignment -name IO_STANDARD "1.2 V" -to refclk4
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to refclk4

# refclk interface
set_location_assignment PIN_AR37 -to refclk0
set_instance_assignment -name IO_STANDARD HCSL -to refclk0
set_location_assignment PIN_AG37 -to refclk1
set_instance_assignment -name IO_STANDARD HCSL -to refclk1

# CXT TX Pin assignments
set_location_assignment PIN_AR41 -to cxl_tx_p[0]
set_location_assignment PIN_AP44 -to cxl_tx_p[1]
set_location_assignment PIN_AL41 -to cxl_tx_p[2]
set_location_assignment PIN_AK44 -to cxl_tx_p[3]
set_location_assignment PIN_AG41 -to cxl_tx_p[4]
set_location_assignment PIN_AF44 -to cxl_tx_p[5]
set_location_assignment PIN_AC41 -to cxl_tx_p[6]
set_location_assignment PIN_AB44 -to cxl_tx_p[7]
set_location_assignment PIN_W41  -to cxl_tx_p[8]
set_location_assignment PIN_V44  -to cxl_tx_p[9]
set_location_assignment PIN_R41  -to cxl_tx_p[10]
set_location_assignment PIN_P44  -to cxl_tx_p[11]
set_location_assignment PIN_L41  -to cxl_tx_p[12]
set_location_assignment PIN_V38  -to cxl_tx_p[13]
set_location_assignment PIN_P38  -to cxl_tx_p[14]
set_location_assignment PIN_K38  -to cxl_tx_p[15]
set_location_assignment PIN_AT40 -to cxl_tx_n[0]
set_location_assignment PIN_AN43 -to cxl_tx_n[1]
set_location_assignment PIN_AM40 -to cxl_tx_n[2]
set_location_assignment PIN_AJ43 -to cxl_tx_n[3]
set_location_assignment PIN_AH40 -to cxl_tx_n[4]
set_location_assignment PIN_AE43 -to cxl_tx_n[5]
set_location_assignment PIN_AD40 -to cxl_tx_n[6]
set_location_assignment PIN_AA43 -to cxl_tx_n[7]
set_location_assignment PIN_Y40  -to cxl_tx_n[8]
set_location_assignment PIN_U43  -to cxl_tx_n[9]
set_location_assignment PIN_T40  -to cxl_tx_n[10]
set_location_assignment PIN_N43  -to cxl_tx_n[11]
set_location_assignment PIN_M40  -to cxl_tx_n[12]
set_location_assignment PIN_U37  -to cxl_tx_n[13]
set_location_assignment PIN_N37  -to cxl_tx_n[14]
set_location_assignment PIN_J37  -to cxl_tx_n[15]


set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_tx_n[*]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_tx_p[*]

# CXT RX Pin assignments
set_location_assignment PIN_AL47 -to cxl_rx_p[0]
set_location_assignment PIN_AG47 -to cxl_rx_p[1]
set_location_assignment PIN_AC47 -to cxl_rx_p[2]
set_location_assignment PIN_W47  -to cxl_rx_p[3]
set_location_assignment PIN_R47  -to cxl_rx_p[4]
set_location_assignment PIN_L47  -to cxl_rx_p[5]
set_location_assignment PIN_G47  -to cxl_rx_p[6]
set_location_assignment PIN_K44  -to cxl_rx_p[7]
set_location_assignment PIN_D46  -to cxl_rx_p[8]
set_location_assignment PIN_F44  -to cxl_rx_p[9]
set_location_assignment PIN_G41  -to cxl_rx_p[10]
set_location_assignment PIN_C41  -to cxl_rx_p[11]
set_location_assignment PIN_B38  -to cxl_rx_p[12]
set_location_assignment PIN_F38  -to cxl_rx_p[13]
set_location_assignment PIN_C35  -to cxl_rx_p[14]
set_location_assignment PIN_G35  -to cxl_rx_p[15]
set_location_assignment PIN_AM46 -to cxl_rx_n[0]
set_location_assignment PIN_AH46 -to cxl_rx_n[1]
set_location_assignment PIN_AD46 -to cxl_rx_n[2]
set_location_assignment PIN_Y46  -to cxl_rx_n[3]
set_location_assignment PIN_T46  -to cxl_rx_n[4]
set_location_assignment PIN_M46  -to cxl_rx_n[5]
set_location_assignment PIN_H46  -to cxl_rx_n[6]
set_location_assignment PIN_J43  -to cxl_rx_n[7]
set_location_assignment PIN_C45  -to cxl_rx_n[8]
set_location_assignment PIN_E43  -to cxl_rx_n[9]
set_location_assignment PIN_H40  -to cxl_rx_n[10]
set_location_assignment PIN_D40  -to cxl_rx_n[11]
set_location_assignment PIN_A37  -to cxl_rx_n[12]
set_location_assignment PIN_E37  -to cxl_rx_n[13]
set_location_assignment PIN_D34  -to cxl_rx_n[14]
set_location_assignment PIN_H34  -to cxl_rx_n[15]

set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_rx_n[*]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_rx_p[*]


#-------DDR4 COMP CH0 PIN ASSIGNMENT--------#

set_location_assignment PIN_CR29 -to mem_a[0][0]
set_location_assignment PIN_CT30 -to mem_a[0][1]
set_location_assignment PIN_CN25 -to mem_a[0][10]
set_location_assignment PIN_CM26 -to mem_a[0][11]
set_location_assignment PIN_CF24 -to mem_a[0][12]
set_location_assignment PIN_CE21 -to mem_a[0][13]
set_location_assignment PIN_CF22 -to mem_a[0][14]
set_location_assignment PIN_CC21 -to mem_a[0][15]
set_location_assignment PIN_CB22 -to mem_a[0][16]
set_location_assignment PIN_CN29 -to mem_a[0][2]
set_location_assignment PIN_CM30 -to mem_a[0][3]
set_location_assignment PIN_CR27 -to mem_a[0][4]
set_location_assignment PIN_CT28 -to mem_a[0][5]
set_location_assignment PIN_CN27 -to mem_a[0][6]
set_location_assignment PIN_CM28 -to mem_a[0][7]
set_location_assignment PIN_CR25 -to mem_a[0][8]
set_location_assignment PIN_CT26 -to mem_a[0][9]
set_location_assignment PIN_CH26 -to mem_act_n[0]
set_location_assignment PIN_CC19 -to mem_alert_n[0]
set_location_assignment PIN_CB20 -to mem_ba[0][0]
set_location_assignment PIN_CE19 -to mem_ba[0][1]
set_location_assignment PIN_CF20 -to mem_bg[0][0]
set_location_assignment PIN_CG27 -to mem_bg[0][1]
set_location_assignment PIN_CL25 -to mem_ck[0][0]
set_location_assignment PIN_CG29 -to mem_cke[0][0]
set_location_assignment PIN_CK26 -to mem_ck_n[0][0]
set_location_assignment PIN_CG25 -to mem_cs_n[0][0]
set_location_assignment PIN_CU15 -to mem_dbi_n[0][0]
set_location_assignment PIN_CU27 -to mem_dbi_n[0][1]
set_location_assignment PIN_CN21 -to mem_dbi_n[0][2]
set_location_assignment PIN_CU21 -to mem_dbi_n[0][3]
set_location_assignment PIN_CN1  -to mem_dbi_n[0][4]
set_location_assignment PIN_CU9  -to mem_dbi_n[0][5]
set_location_assignment PIN_CN9  -to mem_dbi_n[0][6]
set_location_assignment PIN_CN15 -to mem_dbi_n[0][7]
set_location_assignment PIN_CU17 -to mem_dq[0][0]
set_location_assignment PIN_DA17 -to mem_dq[0][1]
set_location_assignment PIN_CU25 -to mem_dq[0][10]
set_location_assignment PIN_DA25 -to mem_dq[0][11]
set_location_assignment PIN_CY30 -to mem_dq[0][12]
set_location_assignment PIN_CV30 -to mem_dq[0][13]
set_location_assignment PIN_CY26 -to mem_dq[0][14]
set_location_assignment PIN_CV26 -to mem_dq[0][15]
set_location_assignment PIN_CR23 -to mem_dq[0][16]
set_location_assignment PIN_CN23 -to mem_dq[0][17]
set_location_assignment PIN_CN19 -to mem_dq[0][18]
set_location_assignment PIN_CR19 -to mem_dq[0][19]
set_location_assignment PIN_CU13 -to mem_dq[0][2]
set_location_assignment PIN_CT24 -to mem_dq[0][20]
set_location_assignment PIN_CM24 -to mem_dq[0][21]
set_location_assignment PIN_CM20 -to mem_dq[0][22]
set_location_assignment PIN_CT20 -to mem_dq[0][23]
set_location_assignment PIN_DA23 -to mem_dq[0][24]
set_location_assignment PIN_CU23 -to mem_dq[0][25]
set_location_assignment PIN_CU19 -to mem_dq[0][26]
set_location_assignment PIN_CV20 -to mem_dq[0][27]
set_location_assignment PIN_CY24 -to mem_dq[0][28]
set_location_assignment PIN_CV24 -to mem_dq[0][29]
set_location_assignment PIN_DA13 -to mem_dq[0][3]
set_location_assignment PIN_CY20 -to mem_dq[0][30]
set_location_assignment PIN_DA19 -to mem_dq[0][31]
set_location_assignment PIN_CT2  -to mem_dq[0][32]
set_location_assignment PIN_CR5  -to mem_dq[0][33]
set_location_assignment PIN_CT6  -to mem_dq[0][34]
set_location_assignment PIN_CM4  -to mem_dq[0][35]
set_location_assignment PIN_CR1  -to mem_dq[0][36]
set_location_assignment PIN_CN5  -to mem_dq[0][37]
set_location_assignment PIN_CM6  -to mem_dq[0][38]
set_location_assignment PIN_CN3  -to mem_dq[0][39]
set_location_assignment PIN_CY18 -to mem_dq[0][4]
set_location_assignment PIN_CV8  -to mem_dq[0][40]
set_location_assignment PIN_CV12 -to mem_dq[0][41]
set_location_assignment PIN_DA7  -to mem_dq[0][42]
set_location_assignment PIN_CU11 -to mem_dq[0][43]
set_location_assignment PIN_CY8  -to mem_dq[0][44]
set_location_assignment PIN_CY12 -to mem_dq[0][45]
set_location_assignment PIN_CU7  -to mem_dq[0][46]
set_location_assignment PIN_DA11 -to mem_dq[0][47]
set_location_assignment PIN_CN7  -to mem_dq[0][48]
set_location_assignment PIN_CM8  -to mem_dq[0][49]
set_location_assignment PIN_CV18 -to mem_dq[0][5]
set_location_assignment PIN_CT12 -to mem_dq[0][50]
set_location_assignment PIN_CM12 -to mem_dq[0][51]
set_location_assignment PIN_CR7  -to mem_dq[0][52]
set_location_assignment PIN_CT8  -to mem_dq[0][53]
set_location_assignment PIN_CR11 -to mem_dq[0][54]
set_location_assignment PIN_CN11 -to mem_dq[0][55]
set_location_assignment PIN_CT14 -to mem_dq[0][56]
set_location_assignment PIN_CM14 -to mem_dq[0][57]
set_location_assignment PIN_CT18 -to mem_dq[0][58]
set_location_assignment PIN_CM18 -to mem_dq[0][59]
set_location_assignment PIN_CV14 -to mem_dq[0][6]
set_location_assignment PIN_CN13 -to mem_dq[0][60]
set_location_assignment PIN_CR13 -to mem_dq[0][61]
set_location_assignment PIN_CR17 -to mem_dq[0][62]
set_location_assignment PIN_CN17 -to mem_dq[0][63]
set_location_assignment PIN_CY14 -to mem_dq[0][7]
set_location_assignment PIN_DA29 -to mem_dq[0][8]
set_location_assignment PIN_CU29 -to mem_dq[0][9]
set_location_assignment PIN_DA15 -to mem_dqs[0][0]
set_location_assignment PIN_DA27 -to mem_dqs[0][1]
set_location_assignment PIN_CR21 -to mem_dqs[0][2]
set_location_assignment PIN_DA21 -to mem_dqs[0][3]
set_location_assignment PIN_CR3  -to mem_dqs[0][4]
set_location_assignment PIN_DA9  -to mem_dqs[0][5]
set_location_assignment PIN_CR9  -to mem_dqs[0][6]
set_location_assignment PIN_CR15 -to mem_dqs[0][7]
set_location_assignment PIN_CY16 -to mem_dqs_n[0][0]
set_location_assignment PIN_CY28 -to mem_dqs_n[0][1]
set_location_assignment PIN_CT22 -to mem_dqs_n[0][2]
set_location_assignment PIN_CY22 -to mem_dqs_n[0][3]
set_location_assignment PIN_CT4  -to mem_dqs_n[0][4]
set_location_assignment PIN_CY10 -to mem_dqs_n[0][5]
set_location_assignment PIN_CT10 -to mem_dqs_n[0][6]
set_location_assignment PIN_CT16 -to mem_dqs_n[0][7]
set_location_assignment PIN_CE23 -to mem_oct_rzqin[0]
set_location_assignment PIN_CL27 -to mem_odt[0][0]
set_location_assignment PIN_CK30 -to mem_par[0]
set_location_assignment PIN_CC23 -to mem_refclk[0]
set_location_assignment PIN_CH28 -to mem_reset_n[0]

#set_location_assignment PIN_AT60 -to mem_dqs_n[0][8]
#set_location_assignment PIN_AV59 -to mem_dqs[0][8]
#set_location_assignment PIN_BC59 -to mem_dbi_n[0][8]
#set_location_assignment PIN_BC61 -to mem_dq[0][64]
#set_location_assignment PIN_AT62 -to mem_dq[0][65]
#set_location_assignment PIN_AV61 -to mem_dq[0][66]
#set_location_assignment PIN_BC57 -to mem_dq[0][67]
#set_location_assignment PIN_BF62 -to mem_dq[0][68]
#set_location_assignment PIN_AT58 -to mem_dq[0][69]
#set_location_assignment PIN_BF58 -to mem_dq[0][70]
#set_location_assignment PIN_AV57 -to mem_dq[0][71]

set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck_n[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_act_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_ba[0][*]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_bg[0][*]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cke[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cs_n[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_odt[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_par[0]
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to mem_refclk[0] -entity ddr4
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dbi_n[0][*]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dq[0][*]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs[0][*]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs_n[0][*]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_a[0][*]

#-------DDR4 COMP CH1 PIN ASSIGNMENT--------# 


set_location_assignment PIN_CE1  -to mem_a[1][0]
set_location_assignment PIN_CF2  -to mem_a[1][1]
set_location_assignment PIN_CC5  -to mem_a[1][10]
set_location_assignment PIN_CB6  -to mem_a[1][11]
set_location_assignment PIN_BY6  -to mem_a[1][12]
set_location_assignment PIN_CA3  -to mem_a[1][13]
set_location_assignment PIN_BY4  -to mem_a[1][14]
set_location_assignment PIN_BU1  -to mem_a[1][15]
set_location_assignment PIN_BV2  -to mem_a[1][16]
set_location_assignment PIN_CE5  -to mem_a[1][2]
set_location_assignment PIN_CF6  -to mem_a[1][3]
set_location_assignment PIN_CE3  -to mem_a[1][4]
set_location_assignment PIN_CF4  -to mem_a[1][5]
set_location_assignment PIN_CC1  -to mem_a[1][6]
set_location_assignment PIN_CB2  -to mem_a[1][7]
set_location_assignment PIN_CC3  -to mem_a[1][8]
set_location_assignment PIN_CB4  -to mem_a[1][9]
set_location_assignment PIN_CK6  -to mem_act_n[1]
set_location_assignment PIN_BU3  -to mem_alert_n[1]
set_location_assignment PIN_BV4  -to mem_ba[1][0]
set_location_assignment PIN_BU5  -to mem_ba[1][1]
set_location_assignment PIN_BV6  -to mem_bg[1][0]
set_location_assignment PIN_CL1  -to mem_bg[1][1]
set_location_assignment PIN_CG3  -to mem_ck[1][0]
set_location_assignment PIN_CG1  -to mem_cke[1][0]
set_location_assignment PIN_CH4  -to mem_ck_n[1][0]
set_location_assignment PIN_CL5  -to mem_cs_n[1][0]
set_location_assignment PIN_BU7  -to mem_dbi_n[1][0]
set_location_assignment PIN_BG9  -to mem_dbi_n[1][1]
set_location_assignment PIN_BL5  -to mem_dbi_n[1][2]
set_location_assignment PIN_BN7  -to mem_dbi_n[1][3]
set_location_assignment PIN_CG17 -to mem_dbi_n[1][4]
set_location_assignment PIN_CC7  -to mem_dbi_n[1][5]
set_location_assignment PIN_CG7  -to mem_dbi_n[1][6]
set_location_assignment PIN_CE17 -to mem_dbi_n[1][7]
set_location_assignment PIN_BU11 -to mem_dq[1][0]
set_location_assignment PIN_BV12 -to mem_dq[1][1]
set_location_assignment PIN_BL7  -to mem_dq[1][10]
set_location_assignment PIN_BG7  -to mem_dq[1][11]
set_location_assignment PIN_BK12 -to mem_dq[1][12]
set_location_assignment PIN_BH12 -to mem_dq[1][13]
set_location_assignment PIN_BH8  -to mem_dq[1][14]
set_location_assignment PIN_BK8  -to mem_dq[1][15]
set_location_assignment PIN_BG5  -to mem_dq[1][16]
set_location_assignment PIN_BG1  -to mem_dq[1][17]
set_location_assignment PIN_BH2  -to mem_dq[1][18]
set_location_assignment PIN_BL1  -to mem_dq[1][19]
set_location_assignment PIN_BV10 -to mem_dq[1][2]
set_location_assignment PIN_BH6  -to mem_dq[1][20]
set_location_assignment PIN_BH4  -to mem_dq[1][21]
set_location_assignment PIN_BG3  -to mem_dq[1][22]
set_location_assignment PIN_BK2  -to mem_dq[1][23]
set_location_assignment PIN_BN11 -to mem_dq[1][24]
set_location_assignment PIN_BM12 -to mem_dq[1][25]
set_location_assignment PIN_BR7  -to mem_dq[1][26]
set_location_assignment PIN_BT8  -to mem_dq[1][27]
set_location_assignment PIN_BR11 -to mem_dq[1][28]
set_location_assignment PIN_BT12 -to mem_dq[1][29]
set_location_assignment PIN_CA7  -to mem_dq[1][3]
set_location_assignment PIN_BM10 -to mem_dq[1][30]
set_location_assignment PIN_BN9  -to mem_dq[1][31]
set_location_assignment PIN_CH14 -to mem_dq[1][32]
set_location_assignment PIN_CG13 -to mem_dq[1][33]
set_location_assignment PIN_CK18 -to mem_dq[1][34]
set_location_assignment PIN_CK14 -to mem_dq[1][35]
set_location_assignment PIN_CG15 -to mem_dq[1][36]
set_location_assignment PIN_CH16 -to mem_dq[1][37]
set_location_assignment PIN_CL17 -to mem_dq[1][38]
set_location_assignment PIN_CL13 -to mem_dq[1][39]
set_location_assignment PIN_CA11 -to mem_dq[1][4]
set_location_assignment PIN_CF8  -to mem_dq[1][40]
set_location_assignment PIN_CB10 -to mem_dq[1][41]
set_location_assignment PIN_CB12 -to mem_dq[1][42]
set_location_assignment PIN_CC11 -to mem_dq[1][43]
set_location_assignment PIN_CE7  -to mem_dq[1][44]
set_location_assignment PIN_CC9  -to mem_dq[1][45]
set_location_assignment PIN_CF12 -to mem_dq[1][46]
set_location_assignment PIN_CE11 -to mem_dq[1][47]
set_location_assignment PIN_CK8  -to mem_dq[1][48]
set_location_assignment PIN_CL7  -to mem_dq[1][49]
set_location_assignment PIN_BY12 -to mem_dq[1][5]
set_location_assignment PIN_CH12 -to mem_dq[1][50]
set_location_assignment PIN_CK12 -to mem_dq[1][51]
set_location_assignment PIN_CG9  -to mem_dq[1][52]
set_location_assignment PIN_CH10 -to mem_dq[1][53]
set_location_assignment PIN_CG11 -to mem_dq[1][54]
set_location_assignment PIN_CL11 -to mem_dq[1][55]
set_location_assignment PIN_CF14 -to mem_dq[1][56]
set_location_assignment PIN_CB14 -to mem_dq[1][57]
set_location_assignment PIN_CB18 -to mem_dq[1][58]
set_location_assignment PIN_CC17 -to mem_dq[1][59]
set_location_assignment PIN_BU9  -to mem_dq[1][6]
set_location_assignment PIN_CC13 -to mem_dq[1][60]
set_location_assignment PIN_CE13 -to mem_dq[1][61]
set_location_assignment PIN_CB16 -to mem_dq[1][62]
set_location_assignment PIN_CC15 -to mem_dq[1][63]
set_location_assignment PIN_BY8  -to mem_dq[1][7]
set_location_assignment PIN_BG11 -to mem_dq[1][8]
set_location_assignment PIN_BL11 -to mem_dq[1][9]
set_location_assignment PIN_CA9  -to mem_dqs[1][0]
set_location_assignment PIN_BL9  -to mem_dqs[1][1]
set_location_assignment PIN_BL3  -to mem_dqs[1][2]
set_location_assignment PIN_BR9  -to mem_dqs[1][3]
set_location_assignment PIN_CL15 -to mem_dqs[1][4]
set_location_assignment PIN_CE9  -to mem_dqs[1][5]
set_location_assignment PIN_CL9  -to mem_dqs[1][6]
set_location_assignment PIN_CE15 -to mem_dqs[1][7]
set_location_assignment PIN_BY10 -to mem_dqs_n[1][0]
set_location_assignment PIN_BK10 -to mem_dqs_n[1][1]
set_location_assignment PIN_BK4  -to mem_dqs_n[1][2]
set_location_assignment PIN_BT10 -to mem_dqs_n[1][3]
set_location_assignment PIN_CK16 -to mem_dqs_n[1][4]
set_location_assignment PIN_CF10 -to mem_dqs_n[1][5]
set_location_assignment PIN_CK10 -to mem_dqs_n[1][6]
set_location_assignment PIN_CF16 -to mem_dqs_n[1][7]
set_location_assignment PIN_CA5  -to mem_oct_rzqin[1]
set_location_assignment PIN_CL3  -to mem_odt[1][0]
set_location_assignment PIN_CH6  -to mem_par[1]
set_location_assignment PIN_CA1  -to mem_refclk[1]
set_location_assignment PIN_CK2  -to mem_reset_n[1]

#set_location_assignment PIN_BC29 -to mem_dbi_n[1][8]
#set_location_assignment PIN_AV29 -to mem_dqs[1][8]
#set_location_assignment PIN_AT30 -to mem_dqs_n[1][8]
#set_location_assignment PIN_AT28 -to mem_dq[1][64]
#set_location_assignment PIN_AT32 -to mem_dq[1][65]
#set_location_assignment PIN_AV27 -to mem_dq[1][66]
#set_location_assignment PIN_BC31 -to mem_dq[1][67]
#set_location_assignment PIN_BF32 -to mem_dq[1][68]
#set_location_assignment PIN_AV31 -to mem_dq[1][69]
#set_location_assignment PIN_BC27 -to mem_dq[1][70]
#set_location_assignment PIN_BF28 -to mem_dq[1][71]
#
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dbi_n[1][*]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs[1][*]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs_n[1][*]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck_n[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_a[1][*]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_act_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_ba[1][*]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_bg[1][*]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cke[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cs_n[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_odt[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_par[1]
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to mem_refclk[1] -entity ddr4

# The generated EMIF buffer selects series 40 ohm for DDR4 RESET_N.  Make the
# board-boundary setting explicit so Quartus can audit both channels as fully
# constrained rather than reporting an incomplete I/O assignment.
set_instance_assignment -name OUTPUT_TERMINATION "SERIES 40 OHM WITHOUT CALIBRATION" -to mem_reset_n[*]
